DanhGia/Website/Models/ErrorViewModel.cs
using System;

namespace WebsiteBlazor.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

DanhGia/Website/Controllers/EvaluationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebsiteBlazor.Controllers
{
    public class EvaluationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DanhGia/Website/Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebsiteBlazor.Models;

namespace WebsiteBlazor.Controllers
{
	public class HomeController : Controller
	{
		private readonly IWebHostEnvironment _appEnvironment;
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger, IWebHostEnvironment appEnvironment)
		{
			_logger = logger;
			_appEnvironment = appEnvironment;
		}

		/// <summary>
		/// GET: Trang chủ
		/// Bộ đếm sử dụng Blazor
		/// </summary>
		/// <returns></returns>
		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		public IActionResult Blazor()
		{
			return View("_Host");
		}

		[HttpGet("api/DocFile/{tenthumuc}/{tenFile}")]
		public IActionResult DocFile(string tenthumuc,string tenFile)
        {
			string filePath = Path.Combine(_appEnvironment.WebRootPath, "files", tenthumuc,tenFile);
            if (System.IO.File.Exists(filePath))
            {
				return Content(System.IO.File.ReadAllText(filePath));
            }
			return NotFound();
        }
	}
}

DanhGia/Website/Views/Evaluation/Index.cshtml
@using WebsiteBlazor.Views.Components
@{
    ViewData["Title"] = "Thuật toán";
}

<component type="typeof(Evaluation)" render-mode="ServerPrerendered" />

@section Scripts{
    <!--Minh họa gọi JS từ C#-->
    <script src="~/js/site.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function Chay() {
            //Chọn dữ liệu
            var dulieu_select = document.getElementById("dulieu").value;
            var url = null
            if (dulieu_select == 1) {
                url = "dulieuchuoi/mangchuoi331kb.txt";
            }
            if (dulieu_select == 2) {
                url = url = "dulieuchuoi/mangchuoi661kb.txt";
            }
            if (dulieu_select == 3) {
                url = "dulieuchuoi/mangchuoi1p766.txt";
            }
            if (dulieu_select == 4) {
                url = "dulieuso/data_s.txt";
            }
            if (dulieu_select == 5) {
                url = "dulieuso/data_m.txt";
            }
            if (dulieu_select == 6) {
                url = "dulieuso/data_xl.txt";
            }

            fetch('https://localhost:44328/api/DocFile/' + url).then(rs => {
                return rs.text()
            }).then(rs => {

                var arr_chuoi = rs.split("\r\n");// chuyển thành mảng chuỗi
                var arr = rs.split("\n"); // chuyển thành mảng số
                //var arr_so = arr.map((item) => parseInt(item));

                // Chọn thuật toán
                var thuattoan_select = document.getElementById("thuattoan").value;
                if (thuattoan_select == 1) {
                    var time_bbsort_chuoi = execution_time(function () {
                        bblSort_chuoi(arr_chuoi);
                    });
                    console.log("thời gian chạy bubble sort chuỗi js là: " + time_bbsort_chuoi + " ms") //ms
                }
                if (thuattoan_select == 2) {
                    var time_slsort_chuoi = execution_time(function () {
                        selectionSort_chuoi(arr_chuoi);
                    });
                    console.log("Thời gian chạy Selection Sort chuỗi JS là: " + time_slsort_chuoi + " ms") //ms
                }
                if (thuattoan_select == 3) {
                    var time_InsertionSort_chuoi = execution_time(function () {
                        insertionSort_chuoi(arr_chuoi);
                    });
                    console.log("Thời gian chạy Insertion Sort chuỗi JS là: " + time_InsertionSort_chuoi + " ms") //ms
                }
                if (thuattoan_select == 4) {
                    var arr_so = arr.map((item) => parseInt(item));

                    var time_bbsort = execution_time(function () {
                        bblSort(arr_so);
                    });
                    console.log("Thời gian chạy Bubble Sort Số JS là: " + time_bbsort + " ms") //ms
                }
                if (thuattoan_select == 5) {
                    var arr_so = arr.map((item) => parseInt(item));

                    var time_slsort = execution_time(function () {
                        selectionSort(arr_so);
                    });
                    console.log("Thời gian chạy Selection Sort Số JS là: " + time_slsort + " ms") //ms
                }
                if (thuattoan_select == 6) {
                    var arr_so = arr.map((item) => parseInt(item));

                    var time_InsertionSort = execution_time(function () {
                        insertionSort(arr_so);
                    });
                    console.log("Thời gian chạy Insertion Sort Số JS là: " + time_InsertionSort + " ms") //ms
                }
            });
        }

        window.ShowAlert = (message) => {
            alert(message);
        }

        window.ShowLog = (message) => {
            console.log(message);
        }

    </script>
}

DanhGia/Website/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Trang chủ";
}

DanhGia/Website/Views/Home/_Host.cshtml
@{
	Layout = "_Layout";
}

<app>
	<component type="typeof(App)" render-mode="ServerPrerendered" />
</app>

DanhGia/Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ASP.NET Core MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
	<base href="~/" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trang web đầu tiên</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Evaluation" asp-action="Index">Evaluation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebsiteBlazor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="_framework/blazor.server.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>